<?php 
/** @var Embitel\Storelocator\Block\Link $block */ ?>
<?php $articleCollection = $block->getCollection(); ?>
<?php if (count($articleCollection)) { ?>
      <h2><?= $block->escapeHtml(__('Store Details')) ?></h2>
      <?php foreach($articleCollection as $post): ?>
          
<?php echo $post->getstore_location(); ?>
<!-- //<p><?php echo $post->getstore_address(); ?></p> -->
</div>
     <?php endforeach; ?> 
<?php } ?> 