 <?php
	$collection = $block->getCollection();
if ($collection->count()) {
?>
<div class="map-data address__block">
<div class="val-container address__location">
<div class="val_container_img address__pic">

    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
        <tr>
            <th><?php echo __('Store Name') ?></th>
            <th><?php echo __('Address') ?></th>
            <th><?php echo __('Mobile Number') ?></th>
            <th><?php echo __('Location ') ?></th>
            
         
        </tr>
        </thead>
        <tbody>
        <?php
				foreach ($collection as $item): ?>
        <tr>
            <!-- <td><?php echo $item->getstore_id() ?></td> -->
            <td><?php echo $item->getstore_name() ?></td>
            <td><?php echo $item->getstore_address() ?></td>
           <td><?php echo $item->getmobile_number() ?></td>
           <td><?php echo $item->getstore_location() ?></td>
          
          
           
           
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
	}
	?> 
